### ISSUE TITLE
Issue with textures in unordered_map

### ISSUE THREAD

**Issue by gxm11** [albin-johansson/centurion#104]
Cannot compile this code:
```c++
#include <centurion.hpp>
#include <unordered_map>

std::unordered_map<int, cen::texture> container;
void fun()
{
    container[0];
}

int main(int argc, char *argv[])
{
    return 0;
}
```

**Comment by albin-johansson** [comment]
Hi!

The problem with this code is that [`cen::texture`](https://albin-johansson.github.io/centurion/classcen_1_1basic__texture.html) _isn't_ default-constructible. `std::unordered_map::operator[]` will try to default-construct the mapped type if there isn't already a value associated with the key. 

However, this doesn't mean that you can't store `cen::texture` instances in a `std::unordered_map`, but the code will have to look something like the following. Also, remember to initialize the library by creating a local instance of the [`cen::library`](https://albin-johansson.github.io/centurion/classcen_1_1library.html) class.

I hope this helps clear things up! 😄 
```C++
#include <centurion.hpp>
#include <unordered_map>  // unordered_map

namespace {

void texture_map_demo()
{
  auto [window, renderer] = cen::make_window_and_renderer();
  
  std::unordered_map<int, cen::texture> textures;
  textures.try_emplace(0, renderer, "path/to/image.png");

  auto& image = textures.at(0);
}

}  // namespace

int main(int, char**)
{
  cen::library centurion;
  texture_map_demo();
  return 0;
}
```

**Comment by gxm11** [comment]
Great! My solution is using `unique_ptr` like:
```c++
unordered_map<int, unique_ptr<cen::texture>> container;
container[0] = make_unique<cen::texture>(renderer, "path/to/image.png");
cen::texture_handle texture{container[0]->get()};
```
But it seems to use `at` and `try_emplace` is much better.

**Comment by gxm11** [comment]
But, why `cen::texture` isn't default-constructible?

**Comment by albin-johansson** [comment]
> Great! My solution is to store unique_ptr in container:

Whilst that works as well, it is slightly inefficient since it introduces an extra indirection. You can think of the `cen::texture` class as a wrapper around `std::unique_ptr<SDL_Texture>` with a custom deleter. On a related note, if you for some reason need to defer the initialization of an object that isn't default-constructible, you can wrap it in a `std::optional`, which is always default-constructible.

> But, why cen::texture isn't default-constructible?

There is no strictly _technical_ reason for this, since as I mentioned earlier, `cen::texture` just wraps an internal `std::unique_ptr`. However, a default-constructed texture would not be a _fully initialized_ object, and almost all usage of such a texture would constitute an error. In a nutshell, all _owning_ (i.e. non-["handle"](https://albin-johansson.github.io/centurion/owners-and-handles.html)) classes in the library have an invariant that the internal pointer or associated data is valid if their constructor didn't throw, which is why `cen::texture` can't be default-constructible. You can read more about principle in the C++ Core Guidelines [here](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c41-a-constructor-should-create-a-fully-initialized-object).

Hopefully, this response provided more answers than questions. 😄

**Comment by gxm11** [comment]
Thank you very much, this reposonse is very useful for me.
