### ISSUE TITLE
Exceptions should store a copy of reason string

### ISSUE THREAD

**Issue by v1993** [albin-johansson/Centurion#129]
Currently, `cen::exception` does not store a copy of a reason string, just a pointer. This may end up problematic when used across threads, since string is dynamically allocated and SDL's internal error variable is thread-local, so it might not exist anymore by the point exception is caught in a different thread. Or if another error is set while unwinding stack (without throwing). As such, `mWhat` should be an `std::string` - it's in exception handling, so performance is hardly critical here.

**Comment by albin-johansson** [comment]
The following is taken from the SDL wiki page for [SDL_GetError](https://wiki.libsdl.org/SDL2/SDL_GetError). As you say, the error strings are thread-local, but they are not dynamically allocated, i.e. no need to free anything.

> Error strings are set per-thread, so an error set in a different thread will not interfere with the current thread's operation. The returned string is internally allocated and must not be freed by the application.

It is a small change to make exception objects store proper strings, so this should not be a problem. This would open up for the possibility of OOM exceptions being thrown in the constructors of our exceptions, due to the extra string allocation. But this is not something that the library even attempts to guard against anyway.

**Comment by v1993** [comment]
> As you say, the error strings are thread-local, but they are not dynamically allocated, i.e. no need to free anything.

Although documentation you've quoted does not say that it not dynamically allocated, merely that it must not be *freed by user* (double-free is a fatal error, after all), looking further into it reveals that they are [using thread-local storage](https://github.com/libsdl-org/SDL/blob/SDL2/src/thread/SDL_thread.c#L221-L280) to store errors. Makes sense.

> This would open up for the possibility of OOM exceptions being thrown in the constructors of our exceptions, due to the extra string allocation.

I mean, doesn't allocating exception alone carry the possibility of OOM error anyways? I guess we can embed fixed-sized buffer (SDL internally uses 128-byte one) into exception object if we want to be extra safe.
