### ISSUE TITLE
rvalue versions of functions that accept `cen::file`

### ISSUE THREAD

**Issue by v1993** [albin-johansson/Centurion#134]
While bd2cbdf5e042b0a64293a1f6850493a0d9faa8cc added lvalue versions of functions accepting `cen::file`, it did not add rvalue versions. Is there a particular reason for that? While this is far from critical, being able to pass files directly from another function is a nice feature. Consider something like:

```cpp
cen::music my_bgm{OpenSoundFile("song1.ogg")}; //< Both opens and closes file
```

This works only with rvalue version in place. Right now, one must be veborse:

```cpp
cen::file bgm_file{OpenSoundFile("song1.ogg")}; //< Opens file
cen::music my_bgm{bgm_file}; //< Does not close file until the end of caller's scope
```

There're no blockers for rvalue version either since `file.release` was upstreamed.

**Comment by v1993** [comment]
Also, it looks like you've decided not to add some of overloads I've included in PR, most notably for `cen::surface` - any particular reason why?

**Comment by albin-johansson** [comment]
The reason is simply to limit the impact on maintainability. The `file` overloads shouldn't even be needed in most cases, you can use the simpler file path overloads instead (see below). So I don't think the burden of having to test and maintain a bunch of niche overloads is worth the minor gain in brevity in some cases. I don't necessarily disagree that some particular code constructs could be nicer by incorporating the rvalue overloads, I just don't think it's worth the effort.

```C++
// This is most likely all you need to do (handles file stuff behind-the-scenes)
cen::music song1 {"song1.ogg"};

// If you worry about the file scope, just close the file.
cen::file song2_file {OpenSoundFile("song2.ogg")};
cen::music song2 {song2_file};
song2_file.close();
```

**Comment by v1993** [comment]
I see. As I've explained in PR, this is largely motivated by my case of having filesystem handled via physfs+physfsrwops, which leads to string-based constructors not being viable for obvious reasons.
