### ISSUE TITLE
vk::required_extensions() returns empty vector

### ISSUE THREAD

**Issue by Compi13** [albin-johansson/centurion#98]
The vector returned by cen::vk::required_extensions() has still size of 0.
The capacity of the vector gets updated:
```cpp
inline auto required_extensions() -> std::optional<std::vector<czstring>>
{
  uint count{};
  if (!SDL_Vulkan_GetInstanceExtensions(nullptr, &count, nullptr))
  {
    return std::nullopt;
  }

  std::vector<czstring> names;
  names.reserve(count);

  if (!SDL_Vulkan_GetInstanceExtensions(nullptr, &count, names.data()))
  {
    return std::nullopt;
  }

  // size of the vector still 0
  return names;
}
```
instead of the size:
```cpp
inline auto required_extensions() -> std::optional<std::vector<czstring>>
{
  uint count{};
  if (!SDL_Vulkan_GetInstanceExtensions(nullptr, &count, nullptr))
  {
    return std::nullopt;
  }

  std::vector<czstring> names{ count };

  if (!SDL_Vulkan_GetInstanceExtensions(nullptr, &count, names.data()))
  {
    return std::nullopt;
  }

  return names;
}
```

**Comment by albin-johansson** [comment]
Hi! 😄 

This does indeed seem like a mistake. I don't know if you've debugged this piece of code, but the problem probably arises, as you pointed out with the size still being zero, due to the fact that the vector doesn't "know" about its actual size. So a temporary workaround could be to access the underlying array using `data()`. Feel free to let me know if I misunderstood the problem!

Thank you for taking the time to open an issue, I'll be sure to look into adding this to the next release.
